// ── 错误码枚举 ──
// 命名规范：{领域}_{具体错误}，全大写蛇形

export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
  AUTH_NO_TENANT: 'AUTH_NO_TENANT',

  // Permission
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  TENANT_REQUIRED: 'TENANT_REQUIRED',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Resource
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',

  // Rate Limit
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  // AI
  AI_GENERATION_FAILED: 'AI_GENERATION_FAILED',
  AI_QUOTA_INSUFFICIENT: 'AI_QUOTA_INSUFFICIENT',
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  AI_TEXT_GENERATION_FAILED: 'AI_TEXT_GENERATION_FAILED',
  AI_INVALID_TEXT_TYPE: 'AI_INVALID_TEXT_TYPE',

  // Storage
  STORAGE_UPLOAD_FAILED: 'STORAGE_UPLOAD_FAILED',
  STORAGE_FILE_TOO_LARGE: 'STORAGE_FILE_TOO_LARGE',

  // Contract
  CONTRACT_SIGN_FAILED: 'CONTRACT_SIGN_FAILED',
  CONTRACT_ALREADY_SIGNED: 'CONTRACT_ALREADY_SIGNED',

  // Internal
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

// ── 标准 API 错误响应 ──
export interface ApiErrorResponse {
  code: ErrorCode;
  message: string;
  details?: unknown;
  statusCode: number;
}
