export const PERMISSIONS = {
  TENANT_READ: 'tenant.read',
  TENANT_MANAGE: 'tenant.manage',
  MEMBER_READ: 'member.read',
  MEMBER_MANAGE: 'member.manage',
  ROLE_READ: 'role.read',
  ROLE_MANAGE: 'role.manage',
  LEAD_READ: 'lead.read',
  LEAD_CREATE: 'lead.create',
  LEAD_UPDATE: 'lead.update',
  LEAD_CONVERT: 'lead.convert',
  CLIENT_READ: 'client.read',
  CLIENT_MANAGE: 'client.manage',
  PROJECT_READ: 'project.read',
  PROJECT_CREATE: 'project.create',
  PROJECT_UPDATE: 'project.update',
  PROJECT_ARCHIVE: 'project.archive',
  CONTRACT_READ: 'contract.read',
  CONTRACT_MANAGE: 'contract.manage',
  PAYMENT_RECORD: 'payment.record',
  TASK_READ: 'task.read',
  TASK_CREATE: 'task.create',
  TASK_ASSIGN: 'task.assign',
  TASK_COMPLETE: 'task.complete',
  CONFIRMATION_READ: 'confirmation.read',
  CONFIRMATION_CREATE: 'confirmation.create',
  CONFIRMATION_RESPOND: 'confirmation.respond',
  ASSET_READ: 'asset.read',
  ASSET_UPLOAD: 'asset.upload',
  ASSET_COMMENT: 'asset.comment',
  ASSET_DOWNLOAD: 'asset.download',
  TIMELINE_READ: 'timeline.read',
  TIMELINE_MANAGE: 'timeline.manage',
  AI_USE: 'ai.use',
  NOTIFICATION_READ: 'notification.read',
  PLATFORM_PLAN_READ: 'platform.plan.read',
  PLATFORM_PLAN_MANAGE: 'platform.plan.manage',
  PLATFORM_SUBSCRIPTION_READ: 'platform.subscription.read',
  PLATFORM_SUBSCRIPTION_MANAGE: 'platform.subscription.manage',
  PLATFORM_SETTING_READ: 'platform.setting.read',
  PLATFORM_SETTING_MANAGE: 'platform.setting.manage',
  PLATFORM_CHANNEL_READ: 'platform.channel.read',
  PLATFORM_CHANNEL_MANAGE: 'platform.channel.manage',
  VENDOR_READ: 'vendor.read',
  VENDOR_MANAGE: 'vendor.manage',
  PUBLIC_CASE_READ: 'public_case.read',
  PUBLIC_CASE_MANAGE: 'public_case.manage',
  TEMPLATE_READ: 'template.read',
  TEMPLATE_MANAGE: 'template.manage',
  MATERIAL_READ: 'material.read',
  MATERIAL_MANAGE: 'material.manage'
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ALL_PERMISSION_CODES = Object.values(PERMISSIONS);
