import { BUILT_IN_ROLES } from './roles';
import { PERMISSIONS, type PermissionCode } from './permissions';

export const BUILT_IN_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  [BUILT_IN_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [BUILT_IN_ROLES.PLANNER]: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_CONVERT,
    PERMISSIONS.CLIENT_READ,
    PERMISSIONS.CLIENT_MANAGE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_ARCHIVE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_MANAGE,
    PERMISSIONS.PAYMENT_RECORD,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.CONFIRMATION_READ,
    PERMISSIONS.CONFIRMATION_CREATE,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.ASSET_UPLOAD,
    PERMISSIONS.ASSET_COMMENT,
    PERMISSIONS.ASSET_DOWNLOAD,
    PERMISSIONS.TIMELINE_READ,
    PERMISSIONS.TIMELINE_MANAGE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.VENDOR_MANAGE,
    PERMISSIONS.PUBLIC_CASE_READ,
    PERMISSIONS.PUBLIC_CASE_MANAGE,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.TEMPLATE_MANAGE,
    PERMISSIONS.MATERIAL_READ,
    PERMISSIONS.MATERIAL_MANAGE
  ],
  [BUILT_IN_ROLES.COUPLE]: [
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.CONFIRMATION_READ,
    PERMISSIONS.CONFIRMATION_RESPOND,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.ASSET_COMMENT,
    PERMISSIONS.ASSET_DOWNLOAD,
    PERMISSIONS.TIMELINE_READ,
    PERMISSIONS.AI_USE,
    PERMISSIONS.NOTIFICATION_READ
  ]
};

export function hasPermission(permissionSet: Iterable<string>, permission: PermissionCode): boolean {
  return new Set(permissionSet).has(permission);
}
