import { BUILT_IN_ROLES } from './roles';
import { PERMISSIONS, type PermissionCode } from './permissions';

export const BUILT_IN_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  [BUILT_IN_ROLES.PLANNER]: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_MANAGE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.ROLE_MANAGE,
    PERMISSIONS.LEAD_READ,
    PERMISSIONS.LEAD_CREATE,
    PERMISSIONS.LEAD_UPDATE,
    PERMISSIONS.LEAD_CONVERT,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_ARCHIVE,
    PERMISSIONS.SCENE_READ,
    PERMISSIONS.SCENE_CREATE,
    PERMISSIONS.SCENE_UPDATE,
    PERMISSIONS.SCENE_DELETE,
    PERMISSIONS.CONTRACT_READ,
    PERMISSIONS.CONTRACT_MANAGE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_ASSIGN,
    PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.ASSET_READ,
    PERMISSIONS.ASSET_UPLOAD,
    PERMISSIONS.ASSET_DOWNLOAD,
    PERMISSIONS.TIMELINE_READ,
    PERMISSIONS.TIMELINE_MANAGE,
    PERMISSIONS.AI_USE,
    PERMISSIONS.AI_GENERATE,
    PERMISSIONS.AI_GENERATION_READ,
    PERMISSIONS.AI_GENERATION_BOOKMARK,
    PERMISSIONS.AI_GENERATION_SERIES,
    PERMISSIONS.AI_TEXT_GENERATE,
    PERMISSIONS.AI_TEXT_GENERATION_READ,
    PERMISSIONS.AI_TEXT_GENERATION_BOOKMARK,
    PERMISSIONS.NOTIFICATION_READ,
    PERMISSIONS.TEMPLATE_READ,
    PERMISSIONS.TEMPLATE_MANAGE,
    PERMISSIONS.MATERIAL_READ,
    PERMISSIONS.MATERIAL_MANAGE,
    PERMISSIONS.MATERIAL_TYPE_READ,
    PERMISSIONS.MATERIAL_TYPE_MANAGE
  ]
};

export function hasPermission(permissionSet: Iterable<string>, permission: PermissionCode): boolean {
  return new Set(permissionSet).has(permission);
}
