import {
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowBackUp,
  IconArrowForwardUp,
  IconArrowRight,
  IconBell,
  IconBold,
  IconBox,
  IconBrandGithub,
  IconBrandTwitter,
  IconBrightness,
  IconBrush,
  IconCalendar,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconChevronsUp,
  IconCircle,
  IconCircleCheck,
  IconCirclePlus,
  IconCircleX,
  IconClipboardText,
  IconClock,
  IconCode,
  IconCommand,
  IconCreditCard,
  IconDeviceLaptop,
  IconDots,
  IconDotsVertical,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileText,
  IconFileTypePdf,
  IconFileTypeDoc,
  IconFileTypeXls,
  IconFileZip,
  IconFolder,
  IconFrame,
  IconGrid3x3,
  IconGripVertical,
  IconHash,
  IconHelpCircle,
  IconHome,
  IconInfoCircle,
  IconItalic,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLayoutSidebar,
  IconLeaf,
  IconLoader2,
  IconLock,
  IconMagnet,
  IconMap,
  IconNeedle,
  IconMapPin,
  IconLogin,
  IconLogout,
  IconMessage,
  IconMinus,
  IconMoon,
  IconMusic,
  IconNotebook,
  IconAlbum,
  IconAward,
  IconBalloon,
  IconBook,
  IconButterfly,
  IconCake,
  IconCamera,
  IconCandle,
  IconClipboardList,
  IconConfetti,
  IconDeviceProjector,
  IconDiamond,
  IconFlower,
  IconGift,
  IconGlassChampagne,
  IconHandStop,
  IconMail,
  IconPennant,
  IconRuler2,
  IconSticker,
  IconTable,
  IconTag,
  IconTicket,
  IconWallpaper,
  IconPencilPlus,
  IconPalette,
  IconPaperclip,
  IconPhone,
  IconPhoto,
  IconPizza,
  IconPlayerStop,
  IconPlus,
  IconProps,
  IconRefresh,
  IconRosetteDiscountCheck,
  IconRuler,
  IconScissors,
  IconSearch,
  IconSelector,
  IconSend,
  IconSettings,
  IconShare,
  IconShield,
  IconSlash,
  IconSparkles,
  IconStack2,
  IconStar,
  IconSun,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTypography,
  IconUnderline,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconUsers,
  IconVideo,
  IconWand,
  IconCrown,
  IconHeart,
  IconBookmark,
  IconCircleDot,
  IconArrowBarDown,
  IconX
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // General
  alertCircle: IconAlertCircle,
  warning: IconAlertTriangle,
  arrowRight: IconArrowRight,
  undo: IconArrowBackUp,
  redo: IconArrowForwardUp,
  refresh: IconRefresh,
  check: IconCheck,
  checks: IconChecks,
  circleCheck: IconCircleCheck,
  close: IconX,
  clock: IconClock,
  code: IconCode,
  dots: IconDots,
  ellipsis: IconDotsVertical,
  externalLink: IconExternalLink,
  help: IconHelpCircle,
  info: IconInfoCircle,
  spinner: IconLoader2,
  search: IconSearch,
  settings: IconSettings,
  trash: IconTrash,

  // Navigation / Chevrons
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronsDown: IconChevronsDown,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  chevronsUp: IconChevronsUp,
  chevronsUpDown: IconSelector,

  // Layout
  dashboard: IconLayoutDashboard,
  kanban: IconLayoutKanban,
  panelLeft: IconLayoutSidebar,

  // User
  user: IconUser,
  user2: IconUserCircle,
  account: IconUserCircle,
  profile: IconUser,
  employee: IconUserX,
  userPen: IconUserEdit,
  teams: IconUsers,

  // Brand
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  logo: IconCommand,

  // Communication
  chat: IconMessage,
  notification: IconBell,
  phone: IconPhone,
  video: IconVideo,
  send: IconSend,
  stop: IconPlayerStop,
  paperclip: IconPaperclip,

  // Files
  page: IconFile,
  post: IconFileText,
  fileTypePdf: IconFileTypePdf,
  fileTypeDoc: IconFileTypeDoc,
  fileTypeXls: IconFileTypeXls,
  fileZip: IconFileZip,
  media: IconPhoto,
  music: IconMusic,
  needle: IconNeedle,
  notebook: IconNotebook,
  hash: IconHash,

  // Actions
  add: IconPlus,
  edit: IconEdit,
  upload: IconUpload,
  share: IconShare,
  location: IconMapPin,
  login: IconLogin,
  logout: IconLogout,
  grid: IconGrid3x3,
  gripVertical: IconGripVertical,

  // Shapes / Indicators
  circle: IconCircle,
  circleX: IconCircleX,
  plusCircle: IconCirclePlus,
  xCircle: IconCircleX,
  minus: IconMinus,

  // Theme
  sun: IconSun,
  moon: IconMoon,
  brightness: IconBrightness,
  laptop: IconDeviceLaptop,
  palette: IconPalette,

  // Commerce / Plans
  billing: IconCreditCard,
  creditCard: IconCreditCard,
  product: IconBox,
  pro: IconCrown,
  exclusive: IconStar,
  sparkles: IconSparkles,
  badgeCheck: IconRosetteDiscountCheck,
  lock: IconLock,
  magnet: IconMagnet,

  // Data / Charts
  trendingDown: IconTrendingDown,
  trendingUp: IconTrendingUp,
  eye: IconEye,
  eyeOff: IconEyeOff,
  adjustments: IconAdjustmentsHorizontal,

  // Text formatting
  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  text: IconTypography,

  // Toast
  toastSuccess: IconCircleCheck,
  toastInfo: IconInfoCircle,
  toastWarning: IconAlertTriangle,
  toastError: IconCircleX,
  toastLoading: IconLoader2,

  // Misc
  pizza: IconPizza,
  workspace: IconFolder,
  shield: IconShield,
  forms: IconClipboardText,
  slash: IconSlash,
  calendar: IconCalendar,
  galleryVerticalEnd: IconStack2,
  moreHorizontal: IconDots,

  // Image actions
  heart: IconHeart,
  bookmark: IconBookmark,
  circleDot: IconCircleDot,
  download: IconArrowBarDown,
  star: IconStar,
  starFilled: IconStar,
  // Material type icons
  frame: IconFrame,
  leaf: IconLeaf,
  brush: IconBrush,
  scissors: IconScissors,
  ruler: IconRuler,
  home: IconHome,
  wand: IconWand,
  map: IconMap,
  // Material type picker icons (wedding semantic)
  diamond: IconDiamond,
  champagne: IconGlassChampagne,
  confetti: IconConfetti,
  balloon: IconBalloon,
  candle: IconCandle,
  pennant: IconPennant,
  flower: IconFlower,
  butterfly: IconButterfly,
  cake: IconCake,
  gift: IconGift,
  mail: IconMail,
  handStop: IconHandStop,
  sticker: IconSticker,
  ticket: IconTicket,
  tag: IconTag,
  award: IconAward,
  wallpaper: IconWallpaper,
  table: IconTable,
  album: IconAlbum,
  projector: IconDeviceProjector,
  clipboardList: IconClipboardList,
  camera: IconCamera,
  book: IconBook,
  ruler2: IconRuler2,
  pencilPlus: IconPencilPlus,
};
